name: pinta-james-carroll
base: core20
version: '1.7'
summary: 'Pinta: Painting Made Simple'
description: |
  Pinta is a free, open source program for drawing and image editing.

  Its goal is to provide users with a simple yet powerful way to draw and manipulate images on Linux, Mac, Windows, and *BSD.

  It is freely available and open source software designed to emulate the functionality of paint.net
grade: stable
confinement: strict
license: MIT

architectures:
  - build-on: amd64
    run-on: amd64

package-repositories:
  - type: apt
    url: https://download.mono-project.com/repo/ubuntu/
    deb-types: [deb]
    components: [main]
    suites: [$SNAPCRAFT_APT_RELEASE]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

  - type: apt
    ppa: pinta-maintainers/pinta-stable

parts:
  pinta:
    plugin: nil
    stage-packages:
      - pinta
      - libglu1-mesa
    after: [gtk2]
      
  gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers
    source-type: git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - libappindicator1
      - locales-all
      - ibus-gtk
      - libibus-1.0-5
      
layout:
  /usr/lib/cli:
    bind: $SNAP/usr/lib/cli
    
plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
    
environment:
  GTK_PATH: $SNAP/lib/gtk-2.0
  GTK_DATA_PREFIX: $SNAP
  XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
  DISABLE_WAYLAND: 1



apps:
  pinta:
    command: bin/desktop-launch mono $SNAP/usr/lib/pinta/Pinta.exe
    plugs: 
      - home
      - removable-media
      - x11
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - network
    environment:
      MONO_GAC_PREFIX: "$SNAP/usr/lib/mono/gac"
      MONO_PATH: "$SNAP/usr/lib/cli/atk-sharp-2.0:$SNAP/usr/lib/cli/gdk-sharp-2.0:$SNAP/usr/lib/cli/glade-sharp-2.0:$SNAP/usr/lib/cli/glib-sharp-2.0:$SNAP/usr/lib/cli/gtk-dotnet-2.0:$SNAP/usr/lib/cli/gtk-sharp-2.0:$SNAP/usr/lib/cli/Mono.Addins-0.2:$SNAP/usr/lib/cli/Mono.Addins.CecilReflector-0.2:$SNAP/usr/lib/cli/Mono.Addins.Gui-0.2:$SNAP/usr/lib/cli/Mono.Addins.Setup-0.2:$SNAP/usr/lib/cli/pango-sharp-2.0"
      MONO_CONFIG: "$SNAP/etc/mono/config"
      C_INCLUDE_PATH: "$SNAP/usr/include"
      ACLOCAL_PATH: "$SNAP/usr/share/aclocal"
