name: pinta
base: core22
version: '2.1.1'
summary: 'Painting Made Simple'
description: |
  Pinta is a freely licensed and cross platform simple drawing application.
  It is designed in lieu of Paint.NET; being both simple to use and powerful for a wide variety of image manipulation purposes.
grade: stable
confinement: strict
license: MIT
compression: lzo

package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/22.04/prod
    components: [main]
    suites: [jammy]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF

parts:
  pinta:
    plugin: nil
    source: https://github.com/pintaproject/pinta.git
    source-commit: bb52f2e05d48a90910de58f02204551d4af80e1e # 2.1.1 tag
    build-packages:
      - build-essential
      - pkg-config
      - autotools-dev
      - autoconf
      - autoconf-archive
      - automake
      - autopoint
      - libtool
      - gettext
      - intltool
      - dotnet-sdk-7.0
    stage-packages:
      - dotnet-runtime-7.0
    override-build: |
      export PATH=/usr/bin:${PATH}
      ./autogen.sh --prefix=${CRAFT_PART_INSTALL}/
      make install

slots:
  pinta-dbus-service:
    interface: dbus
    bus: session
    name: com.github.PintaProject.Pinta

apps:
  pinta:
    command: usr/bin/dotnet $SNAP/lib/pinta/Pinta.dll
    common-id: com.github.PintaProject.Pinta
    plugs:
      - home
      - removable-media
      - x11
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - network
    slots: [pinta-dbus-service]
    extensions: [gnome]
