name: pinta
base: core24
version: 'Pinta-3.0-beta1'
summary: 'Painting Made Simple'
description: |
  Pinta is a freely licensed and cross platform simple drawing application.
  It is designed in lieu of Paint.NET; being both simple to use and powerful for a wide variety of image manipulation purposes.
grade: stable
confinement: strict
license: MIT
compression: lzo

parts:
  pinta:
    plugin: nil
    source: https://github.com/pintaproject/pinta.git
    source-commit: eadb71d7caf96b384a53f808fe1565e84adf578e # Pinta 3.0 Beta 1 tag
    build-packages:
      - build-essential
      - pkg-config
      - autotools-dev
      - autoconf
      - autoconf-archive
      - automake
      - autopoint
      - libtool
      - gettext
      - intltool
      - dotnet-sdk-8.0
    stage-packages:
      - dotnet-runtime-8.0
    override-build: |
      export PATH=/usr/bin:${PATH}
      ./autogen.sh --prefix=${CRAFT_PART_INSTALL}/
      make install

  cleanup:
    plugin: nil
    build-snaps:
      - core24
      - gnome-46-2404
      - mesa-2404
    override-prime: |
      set -eux
      for snap in "core24" "gnome-46-2404" "mesa-2404"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [pinta]



slots:
  pinta-dbus-service:
    interface: dbus
    bus: session
    name: com.github.PintaProject.Pinta

apps:
  pinta:
    command: usr/bin/dotnet $SNAP/lib/pinta/Pinta.dll
    common-id: com.github.PintaProject.Pinta
    plugs:
      - home
      - removable-media
      - network
    slots: [pinta-dbus-service]
    extensions: [gnome]
