name: pinta
base: core20
version: '2.0'
summary: 'Pinta: Painting Made Simple'
description: |
  Pinta is a freely licensed and cross platform simple drawing application.
  It is designed in lieu of Paint.NET; being both simple to use and powerful for a wide variety of image manipulation purposes.
grade: stable
confinement: strict
license: MIT
compression: lzo

package-repositories:
  - type: apt
    url: https://packages.microsoft.com/ubuntu/20.04/prod
    components: [main]
    suites: [focal]
    key-id: BC528686B50D79E339D3721CEB3E94ADBE1229CF

parts:
  pinta:
    plugin: nil
    source: https://github.com/pintaproject/pinta.git
    source-commit: 8f168ea3fd87264ecbbc3ad6eb75d6a4df136960 # 2.0 tag
    build-packages:
      - build-essential
      - pkg-config
      - autotools-dev
      - autoconf
      - autoconf-archive
      - automake
      - autopoint
      - libtool
      - gettext
      - intltool
      - dotnet-sdk-6.0
    stage-packages:
      - libglu1-mesa
      - dotnet-runtime-6.0
    override-build: |
      export PATH=/usr/bin:${PATH}
      ./autogen.sh --prefix=${SNAPCRAFT_PART_INSTALL}/
      make install
      
  cleanup:
    plugin: nil
    build-snaps:
      - core20
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [pinta]

slots:
  pinta-dbus-service:
    interface: dbus
    bus: session
    name: com.github.PintaProject.Pinta

apps:
  pinta:
    command: usr/bin/dotnet $SNAP/lib/pinta/Pinta.dll
    common-id: com.github.PintaProject.Pinta
    plugs: 
      - home
      - removable-media
      - x11
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - unity7
      - network
    slots: [pinta-dbus-service]
    extensions: [gnome-3-38]
